title: AlphaGameDeveloper
url: ""
baseurl: ""

permalink: /blog/:year/:month/:title
excerpt_separator: <!--more-->
markdown: kramdown
highlighter: rouge

#ins_logo: "./bits-logo.png"

tracking_id: "G-Y1CR4RKJQZ"

footer: yes
footer_url: "https://alphagame.dev/"
footer_text: "Website copyright &copy; Damien Boisvert (AlphaGameDeveloper) 2023.  Some rights reserved."

license: "Creative Commons Attribution 4.0 International"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/"
 - name: "About"
   link: "/about"
 - name: "Blog"
   link: /blog
 - name: "School"
   link: /school
 - name: GitHub
   link: https://github.com/AlphaGameDeveloper
