title: AlphaGameDeveloper
url: "https://alphagame.dev/"

# note to self: dont set if it is running in the root dir
# problems like linking to //style.css (note the two slashes)
# will occur.
baseurl: ""

permalink: /blog/:year/:month/:title
excerpt_separator: <!--more-->
markdown: kramdown
highlighter: rouge

#ins_logo: "./bits-logo.png"

tracking_id: "G-Y1CR4RKJQZ"

footer: yes
footer_url: "https://alphagame.dev/"
footer_text: "Website copyright &copy; Damien Boisvert (AlphaGameDeveloper) 2024.  Some rights reserved."

license: "Creative Commons Attribution 4.0 International"

keywords:
  - damien
  - boisvert
  - damienboisvert
  - alphagamedeveloper
  - gamedev
  - alphagame

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/"
 - name: "About"
   link: "/about"
 - name: "Blog"
   link: /blog
# - name: "School"
#   link: /school/
 - name: "AlphaGameBot"
   link: /alphagamebot/
 - name: "Socials"
   link: /links/

author: damienboisvert

feed:
  path: /feed.xml

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap 
