title: AlphaGameDeveloper
url: ""
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://alphagame.dev/"
footer_text: "Website copyright &copy; Damien Boisvert (AlphaGameDeveloper) 2023"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/"
 - name: "About"
   link: "/about"
