name: Bug report
description: Let's quash these bugs in AlphaGameBot!
title: '[BUG]: '
body:
  - type: input
    id: command-used
    attributes:
      label: What command did you experience this bug in?
      description: e.g, /xkcd, /minecraft java, etc.
      placeholder: /placeholder
    validations:
      required: true
  - type: input
    id: command-options
    attributes:
      label: What arguments did you pass into the command
      description: (if applicable)
      placeholder: 'arg1: value1, arg2: value2'
  - type: checkboxes
    id: contributor-policy
    attributes:
      label: Do you agree to the Code of Conduct?
      description: This can be found in `CODE_OF_CONDUCT.md`
      options:
        - label: Do you accept the Contributor Policy?
          required: true
  - type: markdown
